TT#45502 Patch vboxsf when building against Debian/buster fails
Updating to Virtualbox 5.2.18 is a requirement but not enough
yet to build against Debian/buster, as building its vboxsf is
failing:

| /tmp/vbox.0/utils.c: In function ‘sf_init_inode’:
| /tmp/vbox.0/utils.c:165:28: error: passing argument 1 of ‘sf_ftime_from_timespec’ from incompatible pointer type [-Werror=incompatible-pointer-types]
|      sf_ftime_from_timespec(&inode->i_atime, &info->AccessTime);
|                             ^
| /tmp/vbox.0/utils.c:53:13: note: expected ‘struct timespec *’ but argument is of type ‘struct timespec64 *’

Debian's virtualbox 5.2.18-dfsg-2 (which provides a working
virtualbox-guest-dkms) includes a fix to build against kernel 4.18,
see:

  https://tracker.debian.org/news/983571/accepted-virtualbox-5218-dfsg-2-source-into-unstable/

We don't use Debian's virtualbox-guest-dkms though. Instead let's
patch the sources until upstream provides an ISO which includes the
according change for compiling vboxsf against more recent kernel
versions.

I adapted the VirtualBox-kernel-4.18.patch, based on the relevant
change from Debian::

  https://salsa.debian.org/pkg-virtualbox-team/virtualbox/blob/b00c7b4d534c6821c8d1fc1d6c2ce72d5ea0a2d7/debian/patches/kernel-4.18.patch

NOTE: We need to patch the source after it was installed by
`/media/cdrom/VBoxLinuxAdditions.run --nox11`. If we'd invoke
`/media/cdrom/VBoxLinuxAdditions.run` again it would overwrite our
modified sources. Instead patch the source and directly invoke the
relevant steps to compile and install the module.

Change-Id: Iea86c07009838dea5b42af91cbfb0dc233179533